# Generated by Django 3.0.5 on 2020-04-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Judul Berita')),
                ('category', models.CharField(choices=[('Disabilitas', 'disabilitas'), ('Panti Asuhan', 'panti asuhan'), ('Panti Jompo', 'panti jompo')], max_length=100, verbose_name='Kategori')),
                ('categoryslug', models.SlugField(editable=False)),
                ('target', models.IntegerField(verbose_name='Donasi yang diperlukan')),
                ('receive', models.IntegerField(editable=False, verbose_name='Donasi yang diterima')),
                ('image', models.ImageField(upload_to='donate', verbose_name='Gambar')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('slug', models.SlugField(editable=False)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('donation', models.IntegerField(verbose_name='Donasi')),
                ('confirmation', models.IntegerField(editable=False, verbose_name='Konfirmasi')),
                ('verify', models.IntegerField(editable=False, verbose_name='Verifikasi Email')),
                ('barcode', models.CharField(max_length=200, verbose_name='QrCode')),
                ('donateArticle', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='donate.DonateArticle')),
            ],
        ),
    ]
