# Generated by Django 3.0.5 on 2020-04-28 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20200429_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatearticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Waktu dibuat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donatearticle',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Waktu diubah'),
        ),
    ]
